### ISSUE TITLE
Minimal demo app creation error

### ISSUE THREAD

**Issue by nathvi** [anvilistas/amoni#2]
Environment: Windows 10 + VSC

After installing amoni in VSC, 

I'm running the "amoni init" command, 

then just hitting enter at the prompt, which should create the minimal demo app according to the docs

However, I'm getting this error back when just hitting enter at the prompt:

`App folder name [hello_world]: 
Traceback (most recent call last):
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main    
    return _run_code(code, main_globals, None,
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\Scripts\amoni.exe\__main__.py", line 7, in <module>  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\amoni\cli.py", line 28, in init  
    api.init(project, app_folder_name)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\amoni\api.py", line 25, in init  
    cookiecutter(
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\cookiecutter\main.py", line 101, 
in cookiecutter
    result = generate_files(
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\cookiecutter\generate.py", line 272, in generate_files
    project_dir, output_directory_created = render_and_create_dir(
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\cookiecutter\generate.py", line 208, in render_and_create_dir
    raise OutputDirExistsException(msg)
cookiecutter.exceptions.OutputDirExistsException: Error: "." directory already exists`

**Comment by meatballs** [comment]
You need to enter something as the project name at the first prompt

**Comment by nathvi** [comment]
That was it, thanks!
