### ISSUE TITLE
amoni start issue

### ISSUE THREAD

**Issue by nathvi** [anvilistas/amoni#3]
Environment: Windows 10 + VSC

After creating my project in the command line, and changing the directory to the newly created project,
I ran the `amoni start` command and got this error:

`Checking for newer images
Traceback (most recent call last):
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main    
    return _run_code(code, main_globals, None,
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\Scripts\amoni.exe\__main__.py", line 7, in <module>  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\amoni\cli.py", line 37, in start 
    api.pull_image(service)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\amoni\api.py", line 39, in pull_image
    docker.compose.pull([name])
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\python_on_whales\components\compose\cli_wrapper.py", line 297, in pull
    run(full_cmd)
  File "C:\Users\Person\AppData\Local\Programs\Python\Python38\lib\site-packages\python_on_whales\utils.py", line 
177, in run
    raise DockerException(
python_on_whales.exceptions.DockerException: The docker command executed was `C:\Program Files\Docker Toolbox\docker.EXE compose pull app`.
It returned with code 1
The content of stdout is ''
The content of stderr is 'docker: 'compose' is not a docker command.
See 'docker --help'
'`

**Comment by meatballs** [comment]
I may have a step missing from the installation docs. You need to have docker compose installed:

https://docs.docker.com/compose/install/

**Comment by meatballs** [comment]
That's now been added: https://amoni.readthedocs.io/en/latest/installation.html

Thanks for the report!
